AWSTemplateFormatVersion: '2010-09-09'
Description: StartPage - Daily Notion page updater

Parameters:
  NotionToken:
    Type: String
    NoEcho: true
    Description: Notion API token
  PageId:
    Type: String
    Description: Notion page ID
  BlockId:
    Type: String
    Description: Notion block ID for fact update
  City:
    Type: String
    Default: London
    Description: City for weather information
  ICloudUsername:
    Type: String
    Description: iCloud username/email
  ICloudAppPassword:
    Type: String
    NoEcho: true
    Description: iCloud app-specific password
  Timezone:
    Type: String
    Default: UTC
    Description: Timezone for calendar events
  ScheduleExpression:
    Type: String
    Default: 'cron(0 6 * * ? *)'
    Description: EventBridge schedule expression (default daily at 6:00 AM UTC)
  S3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package
  S3Key:
    Type: String
    Default: startpage/package.zip
    Description: S3 key for the Lambda deployment package

Resources:
  StartPageFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StartPageFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: startpage
      Handler: startpage.lambda_handler.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Timeout: 300
      MemorySize: 512
      Role: !GetAtt StartPageFunctionRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Environment:
        Variables:
          NOTION_TOKEN: !Ref NotionToken
          PAGE_ID: !Ref PageId
          BLOCK_ID: !Ref BlockId
          CITY: !Ref City
          ICLOUD_USERNAME: !Ref ICloudUsername
          ICLOUD_APP_PASSWORD: !Ref ICloudAppPassword
          TIMEZONE: !Ref Timezone

  ScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers StartPage update daily
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt StartPageFunction.Arn
          Id: StartPageTarget

  SchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartPageFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduleRule.Arn

  StartPageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StartPageFunction}'
      RetentionInDays: 7

Outputs:
  StartPageFunctionArn:
    Description: StartPage Lambda Function ARN
    Value: !GetAtt StartPageFunction.Arn
  StartPageFunctionRoleArn:
    Description: IAM Role for StartPage Function
    Value: !GetAtt StartPageFunctionRole.Arn
